name: laundry_pelanggan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ! Alert Forget Password
  fluttertoast: ^8.1.1
  uuid: ^3.0.7

  # ! Firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.7
  provider: ^6.0.4

  # ! Decoration
  font_awesome_flutter: ^10.3.0
  iconly: ^1.0.1
  convex_bottom_bar: ^3.1.0+1
  dropdown_search: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # ! Widget
    - assets/images/warning-sign.png
    - assets/images/kategori_photo.png
    - assets/images/laundry.jpg

    # ! Background
    - assets/images/nonauth_background.png
    - assets/images/background.png
